name = "FoSpFloquet"
uuid = "321a32ba-c27a-465a-a448-0b124fab4d50"
version = "1.0.0-DEV"
authors = ["Louis Lammertyn"]

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FoSpCore = "c4c52a10-75be-47fa-9298-4f0d724bc661"
FoSpDynamics = "b136d4ac-0281-4efb-a313-ed4bf251d6d6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
FFTW = "1.10.0"
LinearAlgebra = "1.12.0"
Plots = "1.41.1"
Reexport = "1.2.2"
Revise = "3.12.3"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
